name: Upload to S3

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-central-1'

      - name: Upload index.html to S3
        run: aws s3 cp website/index.html s3://shabnam-cv-cloud-challenge/index.html

      - name: Upload script.js to S3
        run: aws s3 cp website/script.js s3://shabnam-cv-cloud-challenge/script.js

      - name: Upload styles.css to S3
        run: aws s3 cp website/styles.css s3://shabnam-cv-cloud-challenge/styles.css
